/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



import Controlador.Crud;
import Controlador.CrudAlarma;
import Controlador.HoraFecha;
import Controlador.Mail;
import Controlador.WebcamViewerExample;
import Modelo.Alarma;
import Modelo.Movimiento;
import Modelo.Sensores;
import java.awt.Color;
import javax.swing.SwingUtilities;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import java.io.IOException;

import com.github.sarxos.webcam.Webcam;

/**
 *
 * @author SENA
 */
public class Ambientev extends javax.swing.JFrame {

    /**
     * Creates new form Ambiente
     */
    
    public Ambientev() {
        
        initComponents();
        Crud ob= new Crud(tablaseguridad);
        Controlador.HoraFecha h= new HoraFecha(lblhora, lblfecha);
        h.start();
            this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lblAlarma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaseguridad = new javax.swing.JTable();
        lblhora = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        encenderLUZ = new javax.swing.JLabel();
        apagarLUZ = new javax.swing.JLabel();
        abrirPuerta = new javax.swing.JLabel();
        cerrarPuerta = new javax.swing.JLabel();
        encenderLUZaire = new javax.swing.JLabel();
        apagarLUZaire = new javax.swing.JLabel();
        abrirPuertaAire = new javax.swing.JLabel();
        cerrarPuertaAire = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(129, 247, 190));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlarma.setBackground(new java.awt.Color(129, 247, 190));
        lblAlarma.setOpaque(true);
        lblAlarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlarmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlarmaMouseExited(evt);
            }
        });
        panel1.add(lblAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 30, 102, 115));

        jLabel1.setBackground(new java.awt.Color(129, 247, 190));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo DomoticSena.png"))); // NOI18N
        jLabel1.setOpaque(true);
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 11, 110, 110));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("INFORMACION SEGURIDAD");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 564, -1, -1));

        tablaseguridad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TIPO_ALARMA", "DESCRIPCION_ALARMA", "NOMBRE_ALARMA", "TIPO_SENSOR", "NOMBRE_SENSOR", "HORA", "TIPO_MOVIMIENTO", "FECHA"
            }
        ));
        jScrollPane2.setViewportView(tablaseguridad);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 592, 1350, 100));
        panel1.add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1203, 60, 163, 24));
        panel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1203, 30, 163, 24));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo.png"))); // NOI18N
        panel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        encenderLUZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/encendido/encendido3LUZ.gif"))); // NOI18N
        panel1.add(encenderLUZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        apagarLUZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagado/apagado3LUZ.gif"))); // NOI18N
        panel1.add(apagarLUZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        abrirPuerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/encendido/puerta_abrir3LUZ.gif"))); // NOI18N
        panel1.add(abrirPuerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        cerrarPuerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagado/puerta_cerrar3LUZ.gif"))); // NOI18N
        panel1.add(cerrarPuerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        encenderLUZaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/encendido/encendido3LUZ_aireON.gif"))); // NOI18N
        panel1.add(encenderLUZaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        apagarLUZaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagado/apagado3LUZ_aireON.gif"))); // NOI18N
        panel1.add(apagarLUZaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        abrirPuertaAire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/encendido/puerta_abrir3LUZ_aireON.gif"))); // NOI18N
        panel1.add(abrirPuertaAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        cerrarPuertaAire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagado/puerta_cerrar3LUZ_aireON.gif"))); // NOI18N
        panel1.add(cerrarPuertaAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 400));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAlarmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlarmaMouseEntered
        System.out.println("esta bien");
        lblAlarma.setBackground(Color.red);
        Modelo.Movimiento m= new Movimiento();
        Modelo.Sensores s=  new Sensores();
        Controlador.Crud cru= new Crud();
        Controlador.CrudAlarma cr= new CrudAlarma();
        Controlador.Mail mail= new Mail();
        
        
        
        Modelo.Alarma al= new Alarma();
        al.setIdalarma(cr.consultarId());
        al.setTipoalarma("Ingreso No Autorizado");
        al.setDescripcionalarma("Se detecto una persona no autorizada en el ambiente");
        al.setNombrealarma("Acceso");
        
        s.setIdsensor(1);
        m.setFecha(lblfecha.getText());
        m.setHora(lblhora.getText());
        m.setTipomovimiento("Ingreso no Auto.");
        m.setIdsensores(s);
        m.setIdalarma(al);

        cr.registrarAlarma(al);
        cr.reMovimiento(m, al, s);
        cru.llenarTabla2();
        
        
        mail.enviarEmail(m);
        WebcamViewerExample w= new WebcamViewerExample();
        SwingUtilities.invokeLater(w);
        
        // get default webcam and open it
		Webcam webcam = Webcam.getDefault();
		webcam.open();

		// get image
		BufferedImage image = webcam.getImage();

		// save image to PNG file
                try {
            ImageIO.write(image, "JPG", new File("foto.jpg"));
                    System.out.println("La tomo");
                    w.dispose();
        } catch (IOException e) {
                    System.out.println("Error al tomar la foto " + e.getMessage());
        }
		
        
    }//GEN-LAST:event_lblAlarmaMouseEntered
    
    private int hex( String color_hex )
    {
        return Integer.parseInt(color_hex,  16 );
    }
    
    private void lblAlarmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlarmaMouseExited
         System.out.println("esta bien");
         Color color = new Color( hex("81F7BE") );
         lblAlarma.setBackground(color);
    }//GEN-LAST:event_lblAlarmaMouseExited

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel abrirPuerta;
    public javax.swing.JLabel abrirPuertaAire;
    public javax.swing.JLabel apagarLUZ;
    public javax.swing.JLabel apagarLUZaire;
    public javax.swing.JLabel cerrarPuerta;
    public javax.swing.JLabel cerrarPuertaAire;
    public javax.swing.JLabel encenderLUZ;
    public javax.swing.JLabel encenderLUZaire;
    public javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlarma;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    public javax.swing.JPanel panel1;
    public javax.swing.JTable tablaseguridad;
    // End of variables declaration//GEN-END:variables

    private void setMaximumSize(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
